export const config = {
    spawn: { x:0, y: 0, z: 0 },
    dzialki: { x:0, y:0, z:0 },
    plotPrice: 101,
    interactiveBlocks: new Set([
        "minecraft:chest",
        "minecraft:barrel",
        "minecraft:crafting_table",
        "minecraft:anvil",
        "minecraft:enchanting_table",
        "minecraft:grindstone",
        "minecraft:blast_furnace",
        "minecraft:smoker",
        "minecraft:stonecutter",
        "minecraft:lectern",
        "minecraft:loom",
        "minecraft:cartography_table",
        "minecraft:smithing_table",
        "minecraft:ender_chest",
        "minecraft:hopper",
        "minecraft:dispenser",
        "minecraft:dropper",
        "minecraft:beacon",
        "minecraft:bell",
        "minecraft:note_block",
        "minecraft:jukebox",
        "minecraft:armor_stand",
        "minecraft:farmland",
        "minecraft:cauldron",
        "minecraft:brewing_stand",
        "minecraft:flower_pot",
        "minecraft:campfire",
        "minecraft:lever",
        "minecraft:bed"
    ]),
    interactiveTags: [
        "_shulker_box",
        "_bed",
        "_door",
        "_trapdoor",
        "_fence_gate",
        "_button",
        "_pressure_plate",
        "_sign",
        "_hanging_sign"
    ],
}